# Generated by Django 5.0.1 on 2024-01-04 18:14

import apps.Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0003_rename_category_employee_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=apps.Projects.models.user_directory_path)),
                ('slug', models.SlugField(editable=False)),
                ('url', models.CharField(max_length=255)),
                ('developers', models.ManyToManyField(blank=True, null=True, to='Employees.employee')),
            ],
        ),
    ]
