# Generated by Django 5.0.1 on 2024-01-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_project_description_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(),
        ),
    ]
