# Generated by Django 5.0.1 on 2024-02-03 15:42

import apps.Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=apps.Projects.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
