version: '3.11'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  redis:
    image: "redis:alpine"