# Generated by Django 5.0 on 2024-01-02 17:58

import apps.Services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.SmallIntegerField()),
                ('image', models.ImageField(upload_to=apps.Services.models.user_directory_path)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
