# Generated by Django 5.0 on 2024-01-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='messanger',
            new_name='messenger',
        ),
    ]
