# Generated by Django 5.0 on 2024-01-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_rename_messanger_applications_messenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
