# Generated by Django 5.0 on 2023-12-30 19:07

import apps.Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to=apps.Employees.models.user_directory_path),
        ),
    ]
