# Generated by Django 5.0 on 2024-01-02 16:50

import apps.Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_employee_description_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='category',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(max_length=255, upload_to=apps.Employees.models.user_directory_path),
        ),
    ]
