# Generated by Django 5.0.1 on 2024-01-14 17:18

import apps.Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_rename_category_employee_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=apps.Employees.models.certificate_directory_path)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('from_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=apps.Employees.models.skills_directory_path)),
            ],
        ),
    ]
