# Generated by Django 5.0.1 on 2024-01-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_certificates_employmenthistory_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='certificates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.certificates'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.employmenthistory'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.skills'),
        ),
    ]
