# Generated by Django 5.0.1 on 2024-01-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_employee_certificates_employee_employment_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_history',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.AddField(
            model_name='employee',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='Employees.certificates'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_history',
            field=models.ManyToManyField(blank=True, null=True, to='Employees.employmenthistory'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='Employees.skills'),
        ),
    ]
