# Generated by Django 5.0.1 on 2024-01-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0006_remove_employee_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistory',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
