# Generated by Django 5.0.1 on 2024-01-18 00:46

import apps.Employees.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0007_employmenthistory_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.ImageField(max_length=255, upload_to=apps.Employees.models.certificate_directory_path),
        ),
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employees.skillcategory'),
        ),
    ]
