# Generated by Django 5.0.1 on 2024-01-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_skillcategory_alter_certificates_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='certificate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employmenthistory',
            old_name='job_title',
            new_name='title',
        ),
    ]
