# Generated by Django 5.0.1 on 2024-01-30 15:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0009_rename_certificate_name_certificates_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
