# Generated by Django 5.0.1 on 2024-02-03 15:42

import apps.Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0011_alter_certificates_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.ImageField(max_length=1024, upload_to=apps.Employees.models.certificate_directory_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(max_length=1024, upload_to=apps.Employees.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(max_length=1024, upload_to=apps.Employees.models.skills_directory_path),
        ),
    ]
