# Generated by Django 5.0.1 on 2024-02-04 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0012_alter_certificates_image_alter_employee_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_history',
        ),
        migrations.AddField(
            model_name='certificates',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employees.employee'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employees.employee'),
        ),
    ]
