# Generated by Django 5.0.1 on 2024-02-04 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0013_remove_employee_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='Employees.employee'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='Employees.employee'),
        ),
    ]
